# Exception、Error、运行时异常与一般异常有何异同
&emsp;&emsp;在Java中Throwable是所有程序错误处理的父类，它有两个子类：Error和Exception。  
- Error  
&emsp;&emsp;表示由JVM所侦测到的无法预期的错误，由于这是属于JVM层次的严重错误，导致JVM无法继续执行，因此，这是不可捕捉的，无法采取任何恢复的操作，顶多只能显示错误信息。Error类体系描述了Java运行系统中的内部错误以及资源耗尽的情形，应用程序不应该抛出这种类型的对象（一般由虚拟机抛出）。假如出现这种错误，除了尽力使得程序安全推出外，在其他方面是无能为力的。  
- Exception  
&emsp;&emsp;表示可恢复的例外，这是可补足的。  
- 一般异常  
&emsp;&emsp;定义方法时必须声明所有可能会抛出的受查异常（checked exception）。在调用这个方法时，必须捕获它的受查异常，不然就得把它传递下去；checked exception是从java.lang.Exception类衍生出来的。  
&emsp;&emsp;Java 提供了两类主要异常：runtime exception和checked exception。checked exception也就是经常遇到的 IO 异常以及 SQL 异常都是这种异常。对于这种异常，Java 编译器强制要求我们必须对出现的这些异常进行 catch。所以，面对这种异常不管我们是否愿意，只能自己去写一大堆 catch 块去处理可能的异常。这类异常一般是外部错误，例如试图从文件尾后读取数据错误，这并不是程序本身的错误，而是在应用环境中出现的外部错误。  
&emsp;&emsp;但另外一种异常：runtime exception，也叫运行时异常，我们可以不处理。当出现这样的异常时，总是由虚拟机接管。比如：我们从来没有人去处理过NullPointerException异常，它就是运行时异常，并且，这种异常还是最常见的异常之一。RuntimeException体系包括错误的类型转换、数组越界访问和试图访问空指针等等。处理RuntimeException的原则是：假如出现RuntimeException，那么一定是程序员的错误，例如，可以通过检查数组小标和数组边界来避免越界访问异常。  
&emsp;&emsp;出现运行时异常后，系统会把异常一直往上层抛，一直遇到处理代码。如果没有处理块，到最上层，如果是多线程就由Thread.run()抛出，如果是单线程就被main()抛出。抛出之后，如果是线程，这个线程也就推出了。如果主程序抛出的异常，那么这个程序也就退出了。运行时异常是Exception的子类，也就是一般异常的特点，也可以被catch块处理的。只不够往往我们不处理罢了。也就是说，我如果不对运行时异常进行处理，那么出现运行时异常之后，要么线程终止，要么主程序终止。  
&emsp;&emsp;如果不想终止，则必须捕捉所有的运行时异常，决不让这个线程退出。队列里面出现异常数据了，正常的处理应该是把异常数据舍弃，然后记录日志。不应该由于异常数据而影响下面对正常数据的处理。在这个场景这样的处理可能是一个比较好的应用，但并不代表在所有的场景都应该如此。如果在其它场景，遇到了一些错误，如果退出程序比较好，这时你就可以不太理会运行时异常，或者是通过对异常的处理显示的控制程序退出。